### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by velastin** [mihir135/yolov5#2]
Hi. Nice tutorial. I could not find the cudatoolkit. I am using conda and pip3. Any ideas?

**Comment by Mayur2992** [comment]
You must need to install cuda 10.2 then run following command to install torch, torchvision and cuda toolkit.
`conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`

**Comment by velastin** [comment]
Thanks for the mega fast reply! I will try it with 10.0 (which is what I have on my system)

conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
