### ISSUE TITLE
An issue in using the pre-trained model

### ISSUE THREAD

**Issue by rose-jinyang** [mihir135/yolov5#3]
Hello
How are you?
I've tried to train a model but I met an issue when downloading the pre-trained model.

![image](https://user-images.githubusercontent.com/47862419/85953074-82e25b80-b9a0-11ea-9eaf-169b9171870f.png)

So I downloaded the pre-trained models manually and tried to use it but I met this issue again.

![image](https://user-images.githubusercontent.com/47862419/85953116-c89f2400-b9a0-11ea-8ce8-f81fd9f4d969.png)

![image](https://user-images.githubusercontent.com/47862419/85953139-e076a800-b9a0-11ea-9e48-0e5e42b3750c.png)

Please let me know the solution.
Thanks

**Comment by mihir135** [comment]
Hi Rose,

Download the pre-trained model from the following link then try again.

https://mega.nz/file/1XQyTApa

decryption key: hFXzvKCBUJhrwWliI9_B-0StP1y4Z72AFNLmjOpXz9g

**Comment by rose-jinyang** [comment]
Thanks
