### ISSUE TITLE
reboot when using GPU

### ISSUE THREAD

**Issue by fnando1995** [mihir135/yolov5#4]
hello @mihir135 

Is there any explanation why my machine reboots when trying to train the elephant model (or any other)? I tried a different venv with no GPU torch support and it trains the models as expected. But, when using the same code with different venv (with gpu torch support), it makes my machine reboot at the first epoch.

thanks in advance.

note: 
cudatoolkit where not installed in the environment since there is no pip download, any help with that? I do not use conda btw, is that a problem?

**Comment by mihir135** [comment]
@fnando1995 I have tried the same code with several machines. I did not see such kind of issue. However, try to monitor your resources consumption. Or check your system's SMPS is working properly.
