### ISSUE TITLE
nc in models

### ISSUE THREAD

**Issue by velastin** [mihir135/yolov5#5]
Hello. Nice tutorial.
I have started training for my own dataset.
I noted that the models (e.g. yolov5m.yaml) have a line with nc=x where x is the number of classes.
If my data has a different number of classes, do I just change this line and nothing else?

I ask because in v3 and v4, a change in the number of classes also requires a change in the number of "filters" for each of the "scale" layers.

Thanks

**Comment by mihir135** [comment]
No, you don't need to change anything else.

Just the nc parameter.
